timeout: 600s

steps:
  - id: Fetch secret file
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        # Fetch the secret and write it to a file
        gcloud secrets versions access latest --secret=security-definition-file > /workspace/deploy-module/src/main/resources/securityDefinition.json

  - id: Compile image
    name: "gcr.io/cloud-builders/mvn"
    env:
      - 'API_GATEWAY_HOST=${_API_GATEWAY_SERVICE_NAME}'
      - 'GCP_PROJECT_ID=${PROJECT_ID}'
    entrypoint: "bash"
    args:
      - "-cue"
      - |-
        cat /workspace/deploy-module/src/main/resources/securityDefinition.json
        mvn clean compile

  - id: Run unit tests
    name: "gcr.io/cloud-builders/mvn"
    env:
      - 'API_GATEWAY_HOST=${_API_GATEWAY_SERVICE_NAME}'
      - 'GCP_PROJECT_ID=${PROJECT_ID}'
    entrypoint: "bash"
    args:
      - "-cue"
      - |-
        mvn test
